FROM golang:1.13.5 as builder

WORKDIR /app


COPY . .

RUN CGO_ENABLED=0 go build \
    -ldflags "-X main.githash=$(git rev-parse HEAD) -X main.buildstamp=$(date +%Y%m%d.%H%M%S)" \
    -o goapp main.go


##########################################

FROM alpine:latest

WORKDIR /app

COPY  go.mod . 
RUN go mod download

EXPOSE 1323

CMD ["./goapp"]